language: go

go:
  - 1.13.1

services:
  - docker

jobs:
  include:
    - stage: deploy
      script: make build tag push
    - stage: lambda
      if: tag IS present
      script: make build-lambda-function

deploy:
  provider: releases
  api_key:
    secure: II3kQG8zx8SyHQCoRAk+MU7F3i0+4kDft7fDlzAaKLnTlr8HFCxXJXe/CoI1OxlrsDNNclmBn6c6ZsECoiSKthxmXb18+RZnXkJ5vFYlw4UXOcOvZumyjOq3XBVoM/mOvqi4pRNMKRlKmLe32dOAeMExdjZ30A0p3EzkE9itHrK/pwtJ2v9/oMOzrJEgATVevQS5mm3SkAmeOBTggfZStlDGRIX7JivsWxnGDkTlIDj44CZU8UtPVr6Cdoi6N1oiJN7rKt/qzz2h6uIzJqWm9mQMBcSFClSznLG9rbO7ReVnTDpsH84fMAjw51hZpBrAMn+DXHUbkScWsfC/2txxD0hVaZAXhPvkYDnR1WkE9ZOlga46aQlXUfjpnYL0ymRkXHxLxAyPr2SmYWzT3BDTJkCZrqqT0tm0KVixfp1GASqPAANfvTCvWQt1cleEyH5kLCZkQKz8/JU91FAJO2WW1dwOx2/3pMPJRUY7rT71bObRB5VXD9B2DUWcsRloxOdgi4T/9pHCq7C1TNfevOUZVVjO7C4Q38ryecvcmubwMNOrtoREt40Uucq9Wajf0jwCvb//LBeyK3/4rzc0jodoTdrCvMWNOXCydEDGJgeB13bRIqKfzbUjsmEiPiC6FLjqkyyFoR2adENCn/y4hTkRf21LJdyjH+1uYtjW+JcmFbQ=
  file: lambda.zip
  skip_cleanup: true
  on:
    tags: true
    repo: $TRAVIS_REPO_SLUG
    condition: $TRAVIS_BUILD_STAGE_NAME = Lambda
